const express = require('express')
const WorkshopRouter = require('./workshop/workshop.router')
const WholesaleRouter = require('./wholesale/wholesale.router')
const AppRouter = require('./app/app.router')
const ConsentRouter = require('./consent/consent.router')
const InfoRouter = require('./info/info.router')
const ImageRouter = require('./image/image.router')
const VehicleRouter = require('./vehicle/vehicle.router')
const WebOrderRouter = require('./web-order/web-order.router')
const HistoryRouter = require('./history/history.router')
const AuthRouter = require('./auth/auth.router')
const UserRouter = require('./user/user.router')
const AdItemRouter = require('./ad-items/ad-item.router')
const NoticeRouter = require('./notice/notice.router')
const QuoteRouter = require('./quote/quote.router')
const ServicesRouter = require('./services/services.router')
const JobRouter = require('./jobs/jobs.router')
const CollectionPageRouter = require('./collection-page/collection-page.router')

const v3 = new express.Router()

v3.use('/ad-item', AdItemRouter)
v3.use('/app', AppRouter)
v3.use('/auth', AuthRouter)
v3.use('/collection-page', CollectionPageRouter)
v3.use('/consent', ConsentRouter)
v3.use('/history', HistoryRouter)
v3.use('/image', ImageRouter)
v3.use('/info', InfoRouter)
v3.use('/notice', NoticeRouter)
v3.use('/quote', QuoteRouter)
v3.use('/user', UserRouter)
v3.use('/vehicle', VehicleRouter)
v3.use('/web-order', WebOrderRouter)
v3.use('/wholesale', WholesaleRouter)
v3.use('/workshop', WorkshopRouter)
v3.use('/services', ServicesRouter)
v3.use('/jobs', JobRouter)

v3.get('', (req, res) => res.status(200).send({ message: 'Ok' }))

module.exports = v3
